/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsumosRouteImport } from './routes/insumos'
import { Route as MillarayRouteImport } from './routes/millaray'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as Pedidos_onlineRouteImport } from './routes/pedidos_online'
import { Route as ProductosRouteImport } from './routes/productos'
import { Route as TransferenciaRouteImport } from './routes/transferencia'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsumosRoute = InsumosRouteImport.update({
  id: '/insumos',
  path: '/insumos',
  getParentRoute: () => rootRouteImport,
} as any)
const MillarayRoute = MillarayRouteImport.update({
  id: '/millaray',
  path: '/millaray',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const Pedidos_onlineRoute = Pedidos_onlineRouteImport.update({
  id: '/pedidos_online',
  path: '/pedidos_online',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductosRoute = ProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => rootRouteImport,
} as any)
const TransferenciaRoute = TransferenciaRouteImport.update({
  id: '/transferencia',
  path: '/transferencia',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/insumos': typeof InsumosRoute
  '/millaray': typeof MillarayRoute
  '/pedidos': typeof PedidosRoute
  '/pedidos_online': typeof Pedidos_onlineRoute
  '/productos': typeof ProductosRoute
  '/transferencia': typeof TransferenciaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/insumos': typeof InsumosRoute
  '/millaray': typeof MillarayRoute
  '/pedidos': typeof PedidosRoute
  '/pedidos_online': typeof Pedidos_onlineRoute
  '/productos': typeof ProductosRoute
  '/transferencia': typeof TransferenciaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/insumos': typeof InsumosRoute
  '/millaray': typeof MillarayRoute
  '/pedidos': typeof PedidosRoute
  '/pedidos_online': typeof Pedidos_onlineRoute
  '/productos': typeof ProductosRoute
  '/transferencia': typeof TransferenciaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/insumos'
    | '/millaray'
    | '/pedidos'
    | '/pedidos_online'
    | '/productos'
    | '/transferencia'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/insumos'
    | '/millaray'
    | '/pedidos'
    | '/pedidos_online'
    | '/productos'
    | '/transferencia'
  id:
    | '__root__'
    | '/'
    | '/insumos'
    | '/millaray'
    | '/pedidos'
    | '/pedidos_online'
    | '/productos'
    | '/transferencia'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InsumosRoute: typeof InsumosRoute
  MillarayRoute: typeof MillarayRoute
  PedidosRoute: typeof PedidosRoute
  Pedidos_onlineRoute: typeof Pedidos_onlineRoute
  ProductosRoute: typeof ProductosRoute
  TransferenciaRoute: typeof TransferenciaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insumos': {
      id: '/insumos'
      path: '/insumos'
      fullPath: '/insumos'
      preLoaderRoute: typeof InsumosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/millaray': {
      id: '/millaray'
      path: '/millaray'
      fullPath: '/millaray'
      preLoaderRoute: typeof MillarayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos_online': {
      id: '/pedidos_online'
      path: '/pedidos_online'
      fullPath: '/pedidos_online'
      preLoaderRoute: typeof Pedidos_onlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/productos': {
      id: '/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof ProductosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transferencia': {
      id: '/transferencia'
      path: '/transferencia'
      fullPath: '/transferencia'
      preLoaderRoute: typeof TransferenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InsumosRoute: InsumosRoute,
  MillarayRoute: MillarayRoute,
  PedidosRoute: PedidosRoute,
  Pedidos_onlineRoute: Pedidos_onlineRoute,
  ProductosRoute: ProductosRoute,
  TransferenciaRoute: TransferenciaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
